language: python
python:
 - 3.6
install:
  - pip install selenium==3.141.0
before_script:
 - echo $PATH
 - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
 - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
 - export CHROME_BIN=chromium-browser
script:
 - python3 Instagram/src/run_.py
